In [1]:
import quandl
import numpy as np
from sklearn import preprocessing
from sklearn import model_selection
data_frame = quandl.get("YALE/SPCOMP", start_date="1950-01-01", end_date="2019-12-31")
data_frame.head()

S&P Composite  Dividend  Earnings   CPI  Long Interest Rate  \
Year                                                                      
1950-01-31          16.88      1.15   2.33667  23.5            2.320000   
1950-02-28          17.21      1.16   2.35333  23.5            2.340833   
1950-03-31          17.35      1.17   2.37000  23.6            2.361667   
1950-04-30          17.84      1.18   2.42667  23.6            2.382500   
1950-05-31          18.44      1.19   2.48333  23.7            2.403333   

            Real Price  Real Dividend  Real Earnings  \
Year                                                   
1950-01-31  184.702397      12.583398      25.568042   
1950-02-28  188.313285      12.692819      25.750337   
1950-03-31  189.040748      12.747993      25.822857   
1950-04-30  194.379651      12.856950      26.440318   
1950-05-31  200.069332      12.911199      26.943502   

            Cyclically Adjusted PE Ratio  
Year                                      
1950-01-31                     10.745733  
1950-02-28                     10.911564  
1950-03-31                     10.910947  
1950-04-30                     11.178022  
1950-05-31                     11.461543

In [4]:
data_frame = data_frame[['Long Interest Rate', 'Real Price', 'Real Dividend']]
data_frame

Long Interest Rate   Real Price  Real Dividend
Year                                                      
1950-01-31            2.320000   184.702397      12.583398
1950-02-28            2.340833   188.313285      12.692819
1950-03-31            2.361667   189.040748      12.747993
1950-04-30            2.382500   194.379651      12.856950
1950-05-31            2.403333   200.069332      12.911199
...                        ...          ...            ...
2019-08-31            1.630000  2904.059842      56.967809
2019-09-30            1.700000  2986.569552      57.304685
2019-10-31            1.710000  2975.284860            NaN
2019-11-30            1.810000  3104.071562            NaN
2019-12-31            1.910000  3223.380000            NaN

[840 rows x 3 columns]

In [5]:
data_frame.fillna(method='ffill', inplace=True)
data_frame

Long Interest Rate   Real Price  Real Dividend
Year                                                      
1950-01-31            2.320000   184.702397      12.583398
1950-02-28            2.340833   188.313285      12.692819
1950-03-31            2.361667   189.040748      12.747993
1950-04-30            2.382500   194.379651      12.856950
1950-05-31            2.403333   200.069332      12.911199
...                        ...          ...            ...
2019-08-31            1.630000  2904.059842      56.967809
2019-09-30            1.700000  2986.569552      57.304685
2019-10-31            1.710000  2975.284860      57.304685
2019-11-30            1.810000  3104.071562      57.304685
2019-12-31            1.910000  3223.380000      57.304685

[840 rows x 3 columns]

In [6]:
data_frame['Real Price Label'] = data_frame['Real Price'].shift(-3)
data_frame

Long Interest Rate   Real Price  Real Dividend  Real Price Label
Year                                                                        
1950-01-31            2.320000   184.702397      12.583398        194.379651
1950-02-28            2.340833   188.313285      12.692819        200.069332
1950-03-31            2.361667   189.040748      12.747993        202.469952
1950-04-30            2.382500   194.379651      12.856950        185.438831
1950-05-31            2.403333   200.069332      12.911199        195.023530
...                        ...          ...            ...               ...
2019-08-31            1.630000  2904.059842      56.967809       3104.071562
2019-09-30            1.700000  2986.569552      57.304685       3223.380000
2019-10-31            1.710000  2975.284860      57.304685               NaN
2019-11-30            1.810000  3104.071562      57.304685               NaN
2019-12-31            1.910000  3223.380000      57.304685               NaN

[840 rows x 4 columns]

In [7]:
features = np.array(data_frame.drop('Real Price Label', 1))
scaled_features = preprocessing.scale(features)
scaled_features

array([[-1.14839975, -1.13009904, -1.19222544],
       [-1.14114523, -1.12483455, -1.18037146],
       [-1.13389072, -1.12377394, -1.17439424],
       ...,
       [-1.360812  ,  2.9384288 ,  3.65260385],
       [-1.32599032,  3.12619329,  3.65260385],
       [-1.29116864,  3.30013894,  3.65260385]])

In [8]:
scaled_features_latest_3 = scaled_features[-3:]
scaled_features = scaled_features[:-3]
scaled_features

array([[-1.14839975, -1.13009904, -1.19222544],
       [-1.14114523, -1.12483455, -1.18037146],
       [-1.13389072, -1.12377394, -1.17439424],
       ...,
       [-1.38866935,  2.97846643,  3.57443947],
       [-1.38866935,  2.83458633,  3.6161088 ],
       [-1.36429417,  2.95488131,  3.65260385]])

In [9]:
data_frame.dropna(inplace=True)
data_frame

Long Interest Rate   Real Price  Real Dividend  Real Price Label
Year                                                                        
1950-01-31            2.320000   184.702397      12.583398        194.379651
1950-02-28            2.340833   188.313285      12.692819        200.069332
1950-03-31            2.361667   189.040748      12.747993        202.469952
1950-04-30            2.382500   194.379651      12.856950        185.438831
1950-05-31            2.403333   200.069332      12.911199        195.023530
...                        ...          ...            ...               ...
2019-05-31            2.400000  2866.381124      55.925898       2904.059842
2019-06-30            2.060000  2901.408290      56.295329       2986.569552
2019-07-31            1.630000  3002.746469      56.583171       2975.284860
2019-08-31            1.630000  2904.059842      56.967809       3104.071562
2019-09-30            1.700000  2986.569552      57.304685       3223.380000

[837 rows x 4 columns]

In [11]:
label = np.array(data_frame['Real Price Label'])
(features_train, features_test, label_train, label_test) = model_selection.train_test_split(scaled_features, label, test_size=0.1, random_state=8)

In [12]:
label

array([ 194.37965085,  200.06933165,  202.4699521 ,  185.43883071,
        195.02352963,  201.07426721,  207.69723293,  206.43993401,
        203.13981   ,  214.72118858,  220.11898833,  215.57816163,
        218.46848372,  217.72425753,  213.95156178,  217.72425753,
        227.25527838,  231.32657931,  229.26591756,  221.19798068,
        227.15562226,  234.72424189,  232.20727186,  232.79390076,
        231.23029773,  231.13289659,  236.56788   ,  241.53730787,
        242.50037528,  238.64810562,  233.64015506,  241.05577416,
        250.78275506,  253.07891053,  250.92885057,  251.24220338,
        238.86859737,  239.22594607,  229.7939944 ,  233.0562056 ,
        233.14573271,  222.43957361,  228.28229   ,  234.19723048,
        237.35172379,  243.37393829,  248.72701784,  253.98450669,
        265.10263321,  274.63209926,  276.8306855 ,  288.01479814,
        293.75024052,  301.75453545,  308.75869478,  320.84806567,
        336.78467528,  342.852     ,  354.31250225,  351.51960