In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import model_selection
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
file_url = 'https://raw.githubusercontent.com/PacktWorkshops/The-Applied-Artificial-Intelligence-Workshop/master/Datasets/boston_house_price.csv'
df = pd.read_csv(file_url)

features = np.array(df.drop('MEDV', 1))
features

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 2.9600e+02, 1.5300e+01,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 2.4200e+02, 1.7800e+01,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 2.4200e+02, 1.7800e+01,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.7300e+02, 2.1000e+01,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.7300e+02, 2.1000e+01,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.7300e+02, 2.1000e+01,
        7.8800e+00]])

In [2]:
label = np.array(df['MEDV'])
label

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [3]:
scaled_features = preprocessing.scale(features)
scaled_features

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -0.66660821,
        -1.45900038, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.98732948,
        -0.30309415, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.98732948,
        -0.30309415, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ..., -0.80321172,
         1.17646583, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ..., -0.80321172,
         1.17646583, -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ..., -0.80321172,
         1.17646583, -0.66905833]])

In [4]:
poly_1_scaled_features = PolynomialFeatures(degree=1).fit_transform(scaled_features)
poly_1_scaled_features

array([[ 1.        , -0.41978194,  0.28482986, ..., -0.66660821,
        -1.45900038, -1.0755623 ],
       [ 1.        , -0.41733926, -0.48772236, ..., -0.98732948,
        -0.30309415, -0.49243937],
       [ 1.        , -0.41734159, -0.48772236, ..., -0.98732948,
        -0.30309415, -1.2087274 ],
       ...,
       [ 1.        , -0.41344658, -0.48772236, ..., -0.80321172,
         1.17646583, -0.98304761],
       [ 1.        , -0.40776407, -0.48772236, ..., -0.80321172,
         1.17646583, -0.86530163],
       [ 1.        , -0.41500016, -0.48772236, ..., -0.80321172,
         1.17646583, -0.66905833]])

In [5]:
poly_2_scaled_features = PolynomialFeatures(degree=2).fit_transform(scaled_features)
poly_2_scaled_features

array([[ 1.        , -0.41978194,  0.28482986, ...,  2.12868211,
         1.56924581,  1.15683427],
       [ 1.        , -0.41733926, -0.48772236, ...,  0.09186606,
         0.14925549,  0.24249653],
       [ 1.        , -0.41734159, -0.48772236, ...,  0.09186606,
         0.3663582 ,  1.46102192],
       ...,
       [ 1.        , -0.41344658, -0.48772236, ...,  1.38407185,
        -1.15652192,  0.9663826 ],
       [ 1.        , -0.40776407, -0.48772236, ...,  1.38407185,
        -1.0179978 ,  0.74874691],
       [ 1.        , -0.41500016, -0.48772236, ...,  1.38407185,
        -0.78712427,  0.44763905]])

In [6]:
poly_3_scaled_features = PolynomialFeatures(degree=3).fit_transform(scaled_features)
poly_3_scaled_features

array([[ 1.        , -0.41978194,  0.28482986, ..., -2.28953024,
        -1.68782164, -1.24424733],
       [ 1.        , -0.41733926, -0.48772236, ..., -0.04523847,
        -0.07349928, -0.11941484],
       [ 1.        , -0.41734159, -0.48772236, ..., -0.11104103,
        -0.4428272 , -1.76597723],
       ...,
       [ 1.        , -0.41344658, -0.48772236, ..., -1.36060852,
         1.13691611, -0.9500001 ],
       [ 1.        , -0.40776407, -0.48772236, ..., -1.19763962,
         0.88087515, -0.64789192],
       [ 1.        , -0.41500016, -0.48772236, ..., -0.9260248 ,
         0.52663205, -0.29949664]])

In [7]:
poly_1_features_train, poly_1_features_test, poly_label_train, poly_label_test = model_selection.train_test_split(poly_1_scaled_features, label, test_size=0.1, random_state=8)
poly_2_features_train, poly_2_features_test, poly_label_train, poly_label_test = model_selection.train_test_split(poly_2_scaled_features, label, test_size=0.1, random_state=8)
poly_3_features_train, poly_3_features_test, poly_label_train, poly_label_test = model_selection.train_test_split(poly_3_scaled_features, label, test_size=0.1, random_state=8)
model_1 = linear_model.LinearRegression()
model_1.fit(poly_1_features_train, poly_label_train)
model_1_score_train = model_1.score(poly_1_features_train, poly_label_train)
model_1_score_train

0.7406006443486721

In [8]:
model_1_score_test = model_1.score(poly_1_features_test, poly_label_test)
model_1_score_test

0.6772229017901507

In [9]:
model_2 = linear_model.LinearRegression()
model_2.fit(poly_2_features_train, poly_label_train)
model_2_score_train = model_2.score(poly_2_features_train, poly_label_train)
model_2_score_train

0.9251199698832675

In [10]:
model_2_score_test = model_2.score(poly_2_features_test, poly_label_test)
model_2_score_test

0.8253870684280571

In [11]:
model_3 = linear_model.LinearRegression()
model_3.fit(poly_3_features_train, poly_label_train)
model_3_score_train = model_3.score(poly_3_features_train, poly_label_train)
model_3_score_train

0.9910498071896092

In [12]:
model_3_score_test = model_3.score(poly_3_features_test, poly_label_test)
model_3_score_test

-8430.78183931245

In [13]:
model_1_prediction = model_1.predict(poly_1_features_test)
model_2_prediction = model_2.predict(poly_2_features_test)
model_3_prediction = model_3.predict(poly_3_features_test)

df_prediction = pd.DataFrame(poly_label_test)
df_prediction.rename(columns = {0:'label'}, inplace = True)
df_prediction['model_1_prediction'] = pd.DataFrame(model_1_prediction)
df_prediction['model_2_prediction'] = pd.DataFrame(model_2_prediction)
df_prediction['model_3_prediction'] = pd.DataFrame(model_3_prediction)
df_prediction

label  model_1_prediction  model_2_prediction  model_3_prediction
0    18.5           19.269554           19.885620           21.067408
1    12.7           11.434612           14.470337           11.703696
2    21.9           37.610026           32.721497        -3713.860406
3    22.0           26.985628           26.337830            1.711389
4    50.0           40.548986           45.107178         -448.022864
5    36.2           27.730936           26.509888           45.594573
6    16.5           10.601832           18.077148           -6.973548
7    32.4           36.478511           32.267456         1584.038369
8    24.6           29.094356           27.081970           25.674404
9    50.0           34.409453           54.093201         -285.162596
10   13.9           14.138314           15.555481           14.549911
11   11.9            7.143616           14.295105           22.325523
12   16.2           15.145181           15.568420            9.898856
13   21.4           24.640006           22.473389           27.077863
14   14.1           18.286986           15.431091           16.681383
15   22.8           28.722731           27.545044           28.044659
16   20.2           21.954915           23.018860           20.799415
17   20.6           22.242697           21.428589           14.382050
18   21.7           20.525778           23.490112            6.626913
19    8.5            6.123524            3.647705           44.830735
20   19.7           20.941992           20.982605           42.360517
21   24.7           25.283176           23.948181        -1933.416484
22   24.0           30.210006           25.279541         3883.373880
23   31.7           33.246315           35.102905           34.179192
24   28.6           28.029351           30.777344           26.253734
25   33.4           35.604747           37.843628           35.972277
26    7.4            4.072484            7.717102            8.697100
27   14.8           15.357062           15.526855           14.829471
28   25.0           26.446100           22.901733           21.236107
29   17.0           23.139618           12.336243         1313.655700
30   31.0           34.262429           33.495361           31.931148
31   12.6           17.459870           14.574646           16.538190
32   19.4           19.703798           18.277161           18.856206
33   11.9           22.672025           18.018005           24.077838
34   24.8           25.283525           25.321716           12.247411
35   23.7           26.393260           29.153809           23.259279
36   29.0           32.219422           33.910400           40.972135
37   21.6           25.575263           22.962769           22.573236
38   14.3           13.920985           15.894226           15.234361
39   11.5           13.364197           14.815674           12.127128
40   21.7           22.128952           18.801636         1243.717096
41   20.7           21.686098           23.825378           22.295532
42   50.0           35.908786           42.350830           33.081705
43   33.8           34.723780           34.977661           50.412083
44   33.0           23.218126           29.837952          689.720446
45   19.6           18.864385           16.029175           27.249770
46   17.8           19.259586           29.322754         -579.552124
47   21.8           20.448121           17.754700           26.453285
48   19.4           25.689675           18.729675           54.528102
49   29.6           24.659618           24.465759           35.377450
50   17.1           19.966323           17.904297           17.445870