In [1]:
import numpy as np
data_points = np.array([
    [1, 1], 
    [1, 1.5],
    [2, 2],
    [8, 1],
    [8, 0],
    [8.5, 1],
    [6, 1],
    [1, 10],
    [1.5, 10],
    [1.5, 9.5],
    [10, 10],
    [1.5, 8.5]
])
P1 = [1, 1]

In [2]:
from scipy.spatial import distance
r = 2
points1 = np.array([
    p0 for p0 in data_points if distance.euclidean(p0, P1) <= r 
])
points1

array([[1. , 1. ],
       [1. , 1.5],
       [2. , 2. ]])

In [3]:
P2 = [  
    np.mean( points1.transpose()[0] ), 
    np.mean(points1.transpose()[1] ) 
]
P2

[1.3333333333333333, 1.5]

In [4]:
points2 = np.array([
    p0 for p0 in data_points if distance.euclidean( p0, P2) <= r 
])
points2

array([[1. , 1. ],
       [1. , 1.5],
       [2. , 2. ]])

In [5]:
P3 = [8, 1]
points3 = np.array( [
    p0 for p0 in data_points if distance.euclidean(p0, P3) <= r 
])
points3

array([[8. , 1. ],
       [8. , 0. ],
       [8.5, 1. ],
       [6. , 1. ]])

In [6]:
P4 = [  
    np.mean(points3.transpose()[0]), 
    np.mean(points3.transpose()[1]) 
]
P4

[7.625, 0.75]

In [7]:
P5 = [8, 0]
points4 = np.array([
    p0 for p0 in data_points if distance.euclidean(p0, P5) <= r 
])
points4

array([[8. , 1. ],
       [8. , 0. ],
       [8.5, 1. ]])

In [8]:
P6 = [  
    np.mean(points4.transpose()[0]), 
    np.mean(points4.transpose()[1]) 
]
P6

[8.166666666666666, 0.6666666666666666]

In [9]:
P7 = [8.5, 1]
points5 = np.array([
    p0 for p0 in data_points if distance.euclidean(p0, P7) <= r 
])
points5

array([[8. , 1. ],
       [8. , 0. ],
       [8.5, 1. ]])

In [10]:
P8 = [6, 1]
points6 = np.array([
    p0 for p0 in data_points if distance.euclidean(p0, P8) <= r 
])
points6

array([[8., 1.],
       [6., 1.]])

In [11]:
P9 = [  
    np.mean(points6.transpose()[0]), 
    np.mean(points6.transpose()[1]) 
]
P9

[7.0, 1.0]

In [12]:
points7 = np.array([
    p0 for p0 in data_points if distance.euclidean(p0, P9) <= r 
])
points7

array([[8. , 1. ],
       [8. , 0. ],
       [8.5, 1. ],
       [6. , 1. ]])