In [1]:
import numpy as np

In [2]:
real_labels = np.array([True, True, False, True, True])
real_labels

array([ True,  True, False,  True,  True])

In [3]:
model_1_preds = np.array([True, False, False, False, False])
model_1_preds

array([ True, False, False, False, False])

In [4]:
model_2_preds = np.array([True, True, True, True, True])
model_2_preds

array([ True,  True,  True,  True,  True])

In [5]:
model_1_tp_cond = (real_labels == True) & (model_1_preds == True)
model_1_tp_cond

array([ True, False, False, False, False])

In [6]:
model_1_tp = model_1_tp_cond.sum()
model_1_tp

1

In [7]:
model_1_fp = ((real_labels == False) & (model_1_preds == True)).sum()
model_1_fp

0

In [8]:
model_1_fn = ((real_labels == True) & (model_1_preds == False)).sum()
model_1_fn

3

In [9]:
model_1_precision = model_1_tp / (model_1_tp + model_1_fp) 
model_1_precision

1.0

In [10]:
model_1_recall = model_1_tp / (model_1_tp + model_1_fn)
model_1_recall

0.25

In [11]:
model_1_f1 = 2 * model_1_precision * model_1_recall / (model_1_precision + model_1_recall)
model_1_f1

0.4

In [12]:
model_2_tp = ((real_labels == True) & (model_2_preds == True)).sum()
model_2_tp

4

In [13]:
model_2_fp = ((real_labels == False) & (model_2_preds == True)).sum()
model_2_fp

1

In [14]:
model_2_fn = ((real_labels == True) & (model_2_preds == False)).sum()
model_2_fn

0

In [15]:
model_2_precision = model_2_tp / (model_2_tp + model_2_fp) 
model_2_precision

0.8

In [16]:
model_2_recall = model_2_tp / (model_2_tp + model_2_fn)
model_2_recall

1.0

In [17]:
model_2_f1 = 2 * model_2_precision * model_2_recall / (model_2_precision + model_2_recall)
model_2_f1

0.888888888888889