In [48]:
import tensorflow as tf

In [42]:
W = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[1, 6]) 
W

<tf.Tensor: shape=(1, 6), dtype=float32, numpy=array([[1., 2., 3., 4., 5., 6.]], dtype=float32)>

In [43]:
X = tf.constant([7.0, 8.0, 9.0, 10.0, 11.0, 12.0], shape=[6, 1]) 
X

<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.]], dtype=float32)>

In [44]:
b = tf.constant(-88.0)
b

<tf.Tensor: shape=(), dtype=float32, numpy=-88.0>

In [45]:
mult = tf.matmul(W, X)
mult

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[217.]], dtype=float32)>

In [46]:
Z = mult + b
Z

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[129.]], dtype=float32)>

In [47]:
a = tf.math.sigmoid(Z)
a

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>