In [0]:
import numpy as np

In [8]:
A = np.mat([[1,2,3],[4,5,6],[7,8,9]])
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
matmult = A * A
matmult

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [10]:
1 * 1 + 2 * 4 + 3 * 7

30

In [11]:
det = np.linalg.det(A)
det

0.0

In [12]:
transpose = np.matrix.transpose(A)
transpose

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])